project:
  type: website
  output-dir: docs

website:
  title: "Binh Vu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - things.qmd
      - href: projects/index.qmd
        text: Projects
      - href: learning/index.qmd
        text: Learning

  sidebar:
    - id: learning
      style: docked
      collapse-level: 1
      contents:
        - learning/index.qmd
        - section: "Numerical Analysis"
          href: learning/numana/index.qmd
          contents:
            - learning/numana/w1.qmd
            - learning/numana/w2.qmd
            - learning/numana/w3.qmd
        - section: "Regression Analysis"
          href: learning/regress/index.qmd
          contents:
            - learning/regress/w1.qmd
            - learning/regress/w2.qmd
            - learning/regress/w3.qmd
        - section: "Adv. Data Computing"
          href: learning/datacomp/index.qmd
          contents:
            - learning/datacomp/w1.qmd
            - learning/datacomp/w2.qmd
            - learning/datacomp/w3.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    filters:
      - quarto-ext/fontawesome
    toc: true

