project:
  type: website
  output-dir: docs

website:
  title: "Binh Vu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - things.qmd
      - text: learning
        menu:
        - href: numana.qmd
          text: Numerical Analysis
        - href: regress.qmd
          text: Modern Regression
        - href: datacomp.qmd
          text: Adv. Data Computing

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    filters:
      - quarto-ext/fontawesome
    toc: true


